rules:
  no-css-comments: 0
  quotes:
    - 1
    - style: double
  clean-import-paths: 0
  hex-notation: 0
  nesting-depth: 0
  space-before-brace:
    - 2
    - include: true
  leading-zero:
    - 2
    - include: true
  single-line-per-selector:
    - 2
  no-color-literals:
    - 1
  hex-length:
    - 2
  empty-line-between-blocks:
    - 2
  indentation:
    - 2
  property-sort-order: 0
  no-vendor-prefixes: 0