export const Salary = {
  STATUS_APPROVED_TEXT: "Approved",
  STATUS_PAID_TEXT: "Paid",
  STATUS_COMPLETED_TEXT: "Completed",
  STATUS_DRAFT_TEXT: "Draft",

  STATUS_APPROVED_VALUE: 1,
  STATUS_PAID_VALUE: 2,
  STATUS_COMPLETED_VALUE: 3,
  STATUS_DRAFT_VALUE: 4,
};


